### ISSUE TITLE
Nice to have html to pug feature too.

### ISSUE THREAD

**Issue by anoopmundathan** [shidhincr/pug-to-html#5]

**Comment by shidhincr** [comment]
It's actually easy to implement. I was focusing on adding the `locals ( data )` to this first. Once I'm done with that, will add HTML to PUG 

Do you want to come up with a PR ?

**Comment by anoopmundathan** [comment]
I'd love to do my first PR in that case 😄, am newbie here btw.

**Comment by shidhincr** [comment]
No problem. I can help you out. 
Just go ahead !

**Comment by anoopmundathan** [comment]
Getting this error message in console while running the app.
<img width="1265" alt="screen shot 2017-04-18 at 21 14 49" src="https://cloud.githubusercontent.com/assets/3778229/25151151/61cd1050-247c-11e7-9b7a-a90e087d7100.png">

Any idea how to get rid of this?. 

Also, not able to figure out purpose of /api. What functionality that brings to the app?

**Comment by shidhincr** [comment]
Hey sorry for the delay replying you.

The API was introduced previously because of an issue with `pug.compile` in browser.  However, I managed to fix it in this PR #7 

I am going to merge it soon. So you can rebase from master again.
